[theme]
# Tema Púrpura e Laranja (Moderno e Divertido)
primaryColor="#9370DB"  # Medium Purple (Cor principal, puxando o roxo da logo)
backgroundColor="#121212" # Cinza Escuro (Fundo moderno, com mais profundidade que o preto puro)
secondaryBackgroundColor="#FF8C00" # Dark Orange (Cor do Fênix, para destaque em inputs/sidebar)
textColor="#FFFFFF" # Texto branco
font="sans serif"
